spring.application.name=UserService
spring.profiles.active=docker
#Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

internal.secret=super-secret-internal
internal.secret.header=X-Internal-Secret