name: UserService CI pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build-test-analyze:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build app
        run: mvn clean compile

      - name: Run tests
        run: mvn verify

      - name: SonarQube analysis
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=dmitryXdev_InnowiseCourcesUserService \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
          
      - name: Build docker image
        run: docker build -t user-service:latest .
